# Setup
title:               Keelan Cook
tagline:             'Missiologist'
description:         '<img src="/public/Keelan Seal.png" class="center"> The personal website for Keelan Cook. Look here for a current copy of my CV, a list of ongoing projects, and the occasional family and life update.'
url:                 https://keelancook.ml
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Keelan Cook
  url:               https://twitter.com/keelancook
  email:             keelan@ubahouston.org

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: 251844397
