title: "Pathways »"
description: "From your church to the ends of the earth."
remote_theme: pmarsceill/just-the-docs
color_scheme: "pnd"
search_enabled: true
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"


# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  imb:
    permalink: "/:collection/:path/"
    output: true
  planting:
    permalink: "/:collection/:path/"
    output: true
  replanting:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    imb:
      # Give the collection a name
      name: Pathways » IMB
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    planting:
      # Give the collection a name
      name: Pathways » Plant
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    replanting:
      # Give the collection a name
      name: Pathways » Replant
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false