title: "Pathways »"
description: "From your church to the ends of the earth."
remote_theme: pmarsceill/just-the-docs
color_scheme: "pnd"
search_enabled: true
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"
